project:
  type: website

website:
  title: "E155 Karaoke Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project_proposal.qmd
        text: Project Proposal
      - href: midpoint_report.qmd
        text: Midpoint Report

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true